export const FIELD_KEYWORDS_MAP = {
    "Artificial Intelligence": ["ai", "artificial", "artificial intelligence", "machine intel"],
    "Machine Learning": ["ml", "machine learning", "supervised", "unsupervised", "ml engineer"],
    "Deep Learning": ["dl", "deep learning", "neural network", "cnn", "rnn", "transformers"],
    "Data Science": ["ds", "data science", "data analysis", "eda", "data viz"],
    "Data Engineering": ["etl", "pipeline", "data engineer", "big data", "airflow"],
    "Computer Vision": ["cv", "image processing", "object detection", "opencv"],
    "Natural Language Processing": ["nlp", "text processing", "bert", "gpt", "language model"],
    "DevOps": ["devops", "ci/cd", "docker", "kubernetes", "k8s", "ansible"],
    "Cloud Computing": ["cloud", "aws", "azure", "gcp", "cloud engineer", "cloud services"],
    "Cybersecurity": ["cybersecurity", "infosec", "hacking", "penetration testing", "burpsuite"],
    "Blockchain": ["blockchain", "crypto", "ethereum", "web3", "nft", "solidity"],
    "Internet of Things": ["iot", "smart devices", "sensor", "embedded systems"],
    "Frontend Development": ["frontend", "html", "css", "js", "javascript", "react", "vue", "angular"],
    "Backend Development": ["backend", "django", "flask", "nodejs", "api", "rest"],
    "Full Stack Development": ["fullstack", "mern", "mean", "web dev"],
    "Mobile App Development": ["android", "ios", "flutter", "react native", "kotlin", "swift"],
    "Game Development": ["game dev", "unity", "unreal", "gamedev", "level design"],
    "Database Management": ["db", "sql", "nosql", "mongodb", "postgres", "oracle", "mysql"],
    "Software Engineering": ["software", "coding", "sde", "development"],
    "UI/UX Design": ["ui", "ux", "figma", "design", "user interface", "user experience"],
    "Robotics": ["robotics", "ros", "arduino", "automation"],
    "Augmented/Virtual Reality": ["ar", "vr", "virtual reality", "augmented", "xr", "metaverse"],
    "Big Data": ["big data", "hadoop", "spark", "data lake"],
    "Quantum Computing": ["quantum", "qiskit", "quantum computing"],
    "Networking": ["network", "tcp", "ip", "ccna", "firewall", "dns"],
    "Operating Systems": ["linux", "os", "windows kernel", "system programming"],
    "Photography": ["photography", "camera", "dslr", "photo editing", "lightroom", "portrait", "wildlife"],
    "Graphic Design": ["graphic design", "photoshop", "illustrator", "coreldraw", "canva"],
    "Video Editing": ["video edit", "premiere", "after effects", "film making", "davinci", "reels"],
    "Music Production": ["music", "beat making", "fl studio", "logic pro", "composer", "sound design"],
    "Writing & Content": ["writing", "blogging", "creative writing", "copywriting", "author", "novel"],
    "Digital Marketing": ["marketing", "seo", "sem", "social media", "influencer", "ads"],
    "Psychology": ["psychology", "mind", "mental", "therapy", "counseling"],
    "Philosophy": ["philosophy", "thinking", "existence", "logic", "ethics"],
    "Education": ["teacher", "education", "learning", "tutor", "pedagogy", "training"],
    "Sociology": ["society", "culture", "social work", "human behavior", "sociology"],
    "History": ["history", "ancient", "war", "civilization", "historical"],
    "Entrepreneurship": ["startup", "entrepreneur", "founder", "business", "venture"],
    "Finance": ["finance", "investment", "stocks", "trading", "money", "banking"],
    "Economics": ["economics", "macro", "micro", "policy", "economic theory"],
    "Law": ["law", "legal", "lawyer", "court", "case", "justice"],
    "Environmental Science": ["environment", "climate", "sustainability", "eco", "green"],
    "Biotechnology": ["bio", "biotech", "genetics", "bioinformatics"],
    "Civil Engineering": ["civil", "construction", "structures", "bridge", "road"],
    "Mechanical Engineering": ["mechanical", "machines", "automobile", "thermodynamics"],
    "Electrical Engineering": ["electrical", "circuit", "power", "electronics", "vlsi"],
  };
  